import { chromium } from "playwright";
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 900, height: 1400 } });
await p.goto("http://localhost:3000/de/practice?topic=modal-particles&mode=write", { waitUntil: "load" });
await p.waitForTimeout(2500);
const main = await p.evaluate(() => document.querySelector("main").innerText);
const i = main.indexOf("FRAGE"); console.log(main.slice(i, i + 500));
console.log("buttons:", JSON.stringify(await p.evaluate(() => [...document.querySelectorAll("main button")].map((b) => b.innerText.trim()).filter(Boolean).slice(-8))));
console.log("inputs:", await p.locator("main textarea, main input").count());
await b.close();
