import { chromium } from "playwright";
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1100, height: 1300 } });
await p.goto("http://localhost:3000/de/vocabulary", { waitUntil: "load" }); await p.waitForTimeout(3500);
const sec = p.locator("section#slang");
await sec.scrollIntoViewIfNeeded(); await p.waitForTimeout(400);
await sec.screenshot({ path: "/home/g/.claude/jobs/74feb87c/tmp/voc-slang.png" });
console.log((await sec.innerText()).split("\n").slice(0, 26).join(" | "));
const counts = await p.evaluate(() => [...document.querySelectorAll("section[id]")].map((s) => `${s.id}:${s.querySelectorAll("li").length}`).join("  "));
console.log("\nper group (rows):", counts);
await b.close();
