import type { GistTemplate } from "../template.ts";

/**
 * "What is meant?" — a line is heard, four German readings are offered.
 *
 * THE LISTENING QUESTION. Every other kind asks about a word or a form; this
 * one asks the only thing that matters in the moment — did you understand
 * what somebody wants from you. The line is always a real `hear` line from a
 * scene, so it is gated, sourced and has its context one tap away.
 *
 * WRONG ON CONTENT, NEVER ON NUANCE. Each wrong reading is what a German
 * reader plausibly hears — `hei` as `heiss`, `mag` as liking, `ufrucke` as
 * standing up — and each says something plainly DIFFERENT. Where the right
 * reading is itself pragmatic (the scene `indirect-no`), the wrong readings
 * are the literal ones the scene exists to warn against, and the lesson says
 * why.
 */
export const GIST: readonly GistTemplate[] = [
  {
    id: "indirect-no-look",
    heard: { scene: "indirect-no", line: 2 },
    right: "Eher nein — höflich aufgeschoben",
    wrong: ["Ja, das wird sofort erledigt", "Sie sollen es sich selbst ansehen", "Es ist schon entschieden: ja"],
    lesson: "indirect-no",
    listen: { word: "müesst mer no aaluege", means: "müsste man noch anschauen" },
  },
  {
    id: "indirect-no-then",
    heard: { scene: "indirect-no", line: 6 },
    right: "Unverbindlich — vermutlich nicht",
    wrong: ["Fest zugesagt, gleich danach", "Sie sollen sofort nachschauen", "Es ist schon erledigt"],
    lesson: "indirect-no",
    listen: { word: "Mer luegt dänn", means: "Man schaut dann" },
  },
  {
    id: "indirect-no-another-time",
    heard: { scene: "indirect-no", line: 14 },
    right: "Heute nicht — eher ein Nein",
    wrong: ["Ja, gleich jetzt", "Sie sollen es noch einmal sagen", "Es ist alles schon vorbei"],
    lesson: "indirect-no",
    listen: { word: "es anders Mal", means: "ein andermal" },
  },
  {
    id: "indirect-no-depends",
    heard: { scene: "indirect-no", line: 5 },
    right: "Keine Zusage — es ist offen",
    wrong: ["Eine klare Zusage", "Eine Wegbeschreibung", "Eine Frage nach der Uhrzeit"],
    lesson: "indirect-no",
    listen: { word: "drufaa", means: "darauf an" },
  },
  {
    id: "no-rush",
    heard: { scene: "indirect-no", line: 20 },
    right: "Es eilt nicht",
    wrong: ["Es ist sehr dringend", "Sie sind gestresst", "Es muss heute fertig sein"],
    lesson: "small-word",
    listen: { word: "pressiert", means: "eilt" },
  },
  {
    id: "pressant",
    heard: { scene: "at-work", line: 2 },
    right: "Es muss bis Freitag fertig sein",
    wrong: ["Es hat Zeit bis nächsten Monat", "Freitag ist ein freier Tag", "Es war letzten Freitag fertig"],
    lesson: "small-word",
    listen: { word: "pressant", means: "dringend" },
  },
  {
    id: "mag-nuume",
    heard: { scene: "pain", line: 3 },
    right: "Sie hat keine Kraft mehr",
    wrong: ["Sie möchte mehr davon", "Es schmeckt ihr sehr gut", "Sie kommt gleich wieder"],
    lesson: "mag",
    listen: { word: "mag nüme", means: "kann nicht mehr" },
  },
  {
    id: "mag-ufstah",
    heard: { scene: "morning-care", line: 6 },
    right: "Sie will heute nicht aufstehen",
    wrong: ["Sie ist schon aufgestanden", "Sie möchte früher aufstehen als sonst", "Sie kann heute nicht schlafen"],
    lesson: "mag",
    listen: { word: "mag … nöd", means: "mag nicht, fühlt sich nicht danach" },
  },
  {
    id: "mag-nuut",
    heard: { scene: "meals", line: 3 },
    right: "Sie möchte heute nichts essen",
    wrong: ["Sie hat heute schon alles gegessen", "Sie möchte heute alles probieren", "Sie möchte nur Tee"],
    lesson: "mag",
    listen: { word: "nüüt", means: "nichts" },
  },
  {
    id: "wott-hei",
    heard: { scene: "evening-unrest", line: 0 },
    right: "Sie will nach Hause",
    wrong: ["Ihr ist heiss", "Sie ist zu Hause", "Sie will schlafen gehen"],
    lesson: "small-word",
    listen: { word: "hei", means: "nach Hause" },
  },
  {
    id: "am-warte",
    heard: { scene: "handover", line: 4 },
    right: "Sie wartet gerade auf die Tochter",
    wrong: ["Die Tochter wartet auf sie", "Die Tochter war schon da", "Sie will die Tochter nicht sehen"],
    lesson: "verb-frame",
    listen: { word: "isch am warte", means: "wartet gerade" },
  },
  {
    id: "umgheit",
    heard: { scene: "handover", line: 17 },
    right: "Sie wäre gestern fast gestürzt",
    wrong: ["Sie ist gestern umgezogen", "Sie hat gestern fast nichts gegessen", "Sie ist heute gestürzt"],
    lesson: "past",
    listen: { word: "fascht umgheit", means: "fast gestürzt" },
  },
  {
    id: "nod-dusche",
    heard: { scene: "handover", line: 13 },
    right: "Sie will heute nicht duschen",
    wrong: ["Sie hat heute schon geduscht", "Sie darf heute nicht duschen", "Sie möchte zweimal duschen"],
    lesson: "past",
    listen: { word: "well", means: "wolle" },
  },
  {
    id: "dorf-no-oppis",
    heard: { scene: "shopping", line: 10 },
    right: "Ob Sie noch etwas dazu möchten",
    wrong: ["Ob Sie etwas zurückgeben möchten", "Ob Sie eine Tüte brauchen", "Ob Sie schon bezahlt haben"],
    lesson: "offer",
    listen: { word: "Dörf s no öppis sii", means: "Darf es noch etwas sein" },
  },
  {
    id: "scho-dra",
    heard: { scene: "shopping", line: 16 },
    right: "Ob Sie schon an der Reihe sind",
    wrong: ["Ob Sie schon bezahlt haben", "Ob Sie schon einmal hier waren", "Ob Sie etwas daran ändern möchten"],
    lesson: "small-word",
    listen: { word: "dra", means: "an der Reihe" },
  },
  {
    id: "ufrucke",
    heard: { scene: "tram", line: 12 },
    right: "Bitte etwas zur Seite rücken",
    wrong: ["Bitte aufstehen", "Bitte aussteigen", "Bitte das Billett zeigen"],
    lesson: "request",
    listen: { word: "ufrucke", means: "aufrücken" },
  },
  {
    id: "abhocke",
    heard: { scene: "tram", line: 13 },
    right: "Ein Sitzplatz wird Ihnen angeboten",
    wrong: ["Sie sollen aussteigen", "Sie werden nach dem Billett gefragt", "Sie sollen abgeholt werden"],
    lesson: "offer",
    listen: { word: "abhocke", means: "sich hinsetzen" },
  },
  {
    id: "liisliger",
    heard: { scene: "neighbours", line: 2 },
    right: "Bitte abends leiser sein",
    wrong: ["Ob Sie abends Zeit haben", "Bitte abends das Licht löschen", "Ob Sie abends vorbeikommen"],
    lesson: "request",
    listen: { word: "liisliger", means: "leiser" },
  },
  {
    id: "luuted-eifach",
    heard: { scene: "neighbours", line: 17 },
    right: "Klingeln Sie einfach, wenn Sie etwas brauchen",
    wrong: ["Bitte nicht klingeln", "Gehen Sie zur Verwaltung", "Rufen Sie morgen wieder an"],
    lesson: "small-word",
    listen: { word: "lüüted", means: "läuten" },
  },
  {
    id: "blibed-dra",
    heard: { scene: "appointment", line: 16 },
    right: "Bleiben Sie kurz am Telefon",
    wrong: ["Kommen Sie kurz vorbei", "Legen Sie auf", "Warten Sie draussen"],
    lesson: "request",
    listen: { word: "Blibed", means: "Bleiben Sie" },
  },
  {
    id: "lut-aa",
    heard: { scene: "appointment", line: 4 },
    right: "Sie ruft Sie später an",
    wrong: ["Sie schreibt Ihnen später", "Sie kommt später vorbei", "Sie sollen später anrufen"],
    lesson: "person",
    listen: { word: "Ich lüt Ihne … aa", means: "Ich rufe Sie … an" },
  },
  {
    id: "redet-mer",
    heard: { scene: "school-parents", line: 4 },
    right: "Im Kindergarten wird Mundart gesprochen",
    wrong: ["Im Kindergarten wird Hochdeutsch gesprochen", "Die Eltern sollen Mundart lernen", "Im Kindergarten ist es laut"],
    lesson: "person",
    listen: { word: "redet mer", means: "spricht man" },
  },
  {
    id: "luus",
    heard: { scene: "school-parents", line: 14 },
    right: "Es gibt Läuse im Kindergarten",
    wrong: ["Es ist laut im Kindergarten", "Der Kindergarten ist heute zu", "Es gibt Mäuse im Kindergarten"],
    lesson: "es-haet",
    listen: { word: "Es hät", means: "Es gibt" },
  },
  {
    id: "umleitig",
    heard: { scene: "tram", line: 3 },
    right: "Das Tram fährt einen anderen Weg",
    wrong: ["Das Tram fährt normal", "Es gab einen Unfall", "Das Tram ist voll"],
    lesson: "es-haet",
    listen: { word: "Es hät en Umleitig", means: "Es gibt eine Umleitung" },
  },
  {
    id: "znacht",
    heard: { scene: "restaurant", line: 3 },
    right: "Abendessen gibt es ab sechs Uhr",
    wrong: ["Frühstück gibt es ab sechs Uhr", "Abendessen gibt es nur bis sechs Uhr", "Mittagessen gibt es ab sechs Uhr"],
    lesson: "small-word",
    listen: { word: "Znacht", means: "Abendessen" },
  },
  {
    id: "nachtrueh",
    heard: { scene: "neighbours", line: 16 },
    right: "Ab zehn Uhr abends muss es ruhig sein",
    wrong: ["Bis zehn Uhr muss es ruhig sein", "Ab zehn ist die Waschküche frei", "Nur zehn Minuten Ruhe"],
    lesson: "small-word",
    listen: { word: "Ab zäh", means: "Ab zehn" },
  },
  {
    id: "ame",
    heard: { scene: "small-talk", line: 4 },
    right: "Sie gehen normalerweise um zwölf",
    wrong: ["Sie gehen heute ausnahmsweise um zwölf", "Sie gehen erst um zwei", "Sie sind um zwölf zurück"],
    lesson: "small-word",
    listen: { word: "ame", means: "normalerweise" },
  },
  {
    id: "gommer-kafi",
    heard: { scene: "at-work", line: 15 },
    right: "Ein Vorschlag: zusammen Kaffee trinken gehen",
    wrong: ["Die Frage, ob noch Kaffee da ist", "Die Bitte, Kaffee mitzubringen", "Die Frage, ob Sie Kaffee getrunken haben"],
    lesson: "verb-frame",
    listen: { word: "Gömmer … go neh", means: "Gehen wir … nehmen" },
  },
  {
    id: "mini-maschine",
    heard: { scene: "laundry-room", line: 5 },
    right: "Die Maschine ist noch besetzt",
    wrong: ["Die Maschine ist kaputt", "Die Maschine ist jetzt frei", "Die Maschine gehört Ihnen"],
    lesson: "small-word",
    listen: { word: "gäll", means: "nicht wahr" },
  },
  {
    id: "uber-d-ziit",
    heard: { scene: "laundry-room", line: 10 },
    right: "Sie haben gestern Ihre Zeit überzogen",
    wrong: ["Sie waren gestern pünktlich", "Sie hatten gestern keine Zeit", "Sie sind morgen an der Reihe"],
    lesson: "past",
    listen: { word: "sind … gsi", means: "waren" },
  },
  {
    id: "verstahsch",
    heard: { scene: "small-talk", line: 12 },
    right: "Ob Sie schon etwas Zürichdeutsch verstehen",
    wrong: ["Ob Sie aus Zürich kommen", "Ob Sie Zürichdeutsch lernen wollen", "Ob Sie Hochdeutsch verstehen"],
    lesson: "small-word",
    listen: { word: "ächli", means: "ein bisschen" },
  },
  {
    id: "versichertecharte",
    heard: { scene: "appointment", line: 1 },
    right: "Ob Sie die Versichertenkarte mitgebracht haben",
    wrong: ["Ob Sie versichert werden möchten", "Ob Sie mit Karte bezahlen", "Ob Sie eine Karte brauchen"],
    lesson: "small-word",
    listen: { word: "debii", means: "dabei" },
  },
  {
    id: "uusbuecht",
    heard: { scene: "appointment", line: 12 },
    right: "Diese Woche gibt es keinen Termin mehr",
    wrong: ["Diese Woche ist die Praxis zu", "Es gibt noch viele freie Termine", "Sie haben diese Woche einen Termin"],
    lesson: "small-word",
    listen: { word: "uusbuecht", means: "ausgebucht" },
  },
  {
    id: "vorbiiluege",
    heard: { scene: "handover", line: 6 },
    right: "Eine Bitte: heute Nachmittag bei ihr vorbeischauen",
    wrong: ["Sie war heute Nachmittag schon da", "Eine Frage, ob sie heute Nachmittag Besuch hat", "Eine Bitte, sie heute nicht zu stören"],
    lesson: "request",
    listen: { word: "verbiiluege", means: "vorbeischauen" },
  },
];
