import type { ExampleRef, LineRef, TransformTemplate, Written } from "../template.ts";

/**
 * "Which sentence says exactly this?" — German shown, four Zurich sentences
 * offered, one of which means it.
 *
 * THE GRAMMAR QUESTION A GERMAN READER ACTUALLY NEEDS. Not "conjugate this",
 * which a reader of German never has to do in order to understand, but "hear
 * the difference": `Mir warted` against `Si warted`, `wo mich gsee hät`
 * against `wo ich gsee ha`, `go` against `cho`. Each wrong option is correct
 * Zurich German that says something else — so nothing here asks anybody to
 * spot an invented error, and nothing wrong is ever printed as Zurich German.
 *
 * WHAT MAKES IT MARKABLE: every option carries its own German, and the
 * validator refuses a record where a wrong option's German equals the right
 * one's. Four sentences, four different meanings, one of them the prompt.
 */

const L = (scene: string, line: number): LineRef => ({ scene, line });
const X = (topic: string, example: number): ExampleRef => ({ topic, example });
const W = (target: string, bridge: string): Written => ({ target, bridge, cite: "idiotikon" });

export const TRANSFORM: readonly TransformTemplate[] = [
  {
    id: "went-home",
    about: { topic: "no-preterite" },
    right: X("no-preterite", 0),
    wrong: [
      W("Ich gang hüt hei.", "Ich gehe heute nach Hause."),
      W("Mir sind geschter hei gange.", "Wir gingen gestern nach Hause."),
      W("Ich bi geschter nöd hei gange.", "Ich ging gestern nicht nach Hause."),
    ],
    lesson: "past",
    listen: { word: "bi … gange", means: "ging (bin gegangen)" },
  },
  {
    id: "said-nothing",
    about: { topic: "no-preterite" },
    right: X("no-preterite", 1),
    wrong: [
      W("Si seit nüüt.", "Sie sagt nichts."),
      W("Er hät nüüt gseit.", "Er sagte nichts."),
      W("Si hät öppis gseit.", "Sie sagte etwas."),
    ],
    lesson: "past",
    listen: { word: "hät … gseit", means: "sagte (hat gesagt)" },
  },
  {
    id: "mountains",
    about: { topic: "no-preterite" },
    right: L("small-talk", 1),
    wrong: [
      W("Ganz guet, mir gönd i d Bärge.", "Ganz gut, wir gehen in die Berge."),
      W("Ganz guet, ich bi i de Bärge gsi.", "Ganz gut, ich war in den Bergen."),
      W("Ganz guet, mir sind i de Stadt gsi.", "Ganz gut, wir waren in der Stadt."),
    ],
    lesson: "past",
    listen: { word: "sind … gsi", means: "waren" },
  },
  {
    id: "waiting-ten",
    about: { topic: "unified-plural" },
    right: L("tram", 4),
    wrong: [
      W("Ich warte scho zäh Minute.", "Ich warte schon zehn Minuten."),
      W("Si warted scho zäh Minute.", "Sie warten schon zehn Minuten."),
      W("Mir warted scho zwei Minute.", "Wir warten schon zwei Minuten."),
    ],
    lesson: "person",
    listen: { word: "Mir warted", means: "Wir warten" },
  },
  {
    id: "children-forest",
    about: { topic: "unified-plural" },
    right: L("school-parents", 10),
    wrong: [
      W("S Chind gaht hüt in Wald.", "Das Kind geht heute in den Wald."),
      W("D Chind sind hüt im Wald gsi.", "Die Kinder waren heute im Wald."),
      W("D Chind gönd morn in Wald.", "Die Kinder gehen morgen in den Wald."),
    ],
    lesson: "person",
    listen: { word: "D Chind gönd", means: "Die Kinder gehen" },
  },
  {
    id: "coming-tonight",
    about: { topic: "unified-plural" },
    right: X("unified-plural", 1),
    wrong: [
      W("Chunnsch du hüt no?", "Kommst du heute noch?"),
      W("Chömed Sie hüt no?", "Kommen Sie heute noch?"),
      W("Chömed er morn?", "Kommt ihr morgen?"),
    ],
    lesson: "person",
    listen: { word: "Chömed er", means: "Kommt ihr" },
  },
  {
    id: "man-standing",
    about: { topic: "wo-relative" },
    right: X("wo-relative", 0),
    wrong: [
      W("De Maa, wo dört gstande isch.", "Der Mann, der dort stand."),
      W("Wo staht de Maa?", "Wo steht der Mann?"),
      W("De Maa staht dört.", "Der Mann steht dort."),
    ],
    lesson: "relative",
    listen: { word: "wo", means: "der, die, das (Relativpronomen)" },
  },
  {
    id: "woman-seen",
    about: { topic: "wo-relative" },
    right: X("wo-relative", 1),
    wrong: [
      W("D Frau, wo mich gsee hät.", "Die Frau, die mich gesehen hat."),
      W("Wo han ich d Frau gsee?", "Wo habe ich die Frau gesehen?"),
      W("D Frau hät mich gsee.", "Die Frau hat mich gesehen."),
    ],
    lesson: "relative",
    listen: { word: "wo ich gsee ha", means: "die ich gesehen habe" },
  },
  {
    id: "doctor-on-phone",
    about: { topic: "am-progressive" },
    right: L("appointment", 2),
    wrong: [
      W("De Dokter hät grad telefoniert.", "Der Arzt hat gerade telefoniert."),
      W("De Dokter isch grad am schriibe.", "Der Arzt schreibt gerade."),
      W("De Dokter chunt spööter.", "Der Arzt kommt später."),
    ],
    lesson: "verb-frame",
    listen: { word: "isch … am telefoniere", means: "telefoniert gerade" },
  },
  {
    id: "still-planning",
    about: { topic: "am-progressive" },
    right: L("at-work", 12),
    wrong: [
      W("Mir händ scho plant.", "Wir haben schon geplant."),
      W("Ich bi no am plane.", "Ich plane noch."),
      W("Mir sind no am schaffe.", "Wir arbeiten noch."),
    ],
    lesson: "verb-frame",
    listen: { word: "sind no am plane", means: "planen noch" },
  },
  {
    id: "working-now",
    about: { topic: "am-progressive" },
    right: X("am-progressive", 0),
    wrong: [
      W("Ich ha gschaffet.", "Ich habe gearbeitet."),
      W("Er isch am schaffe.", "Er arbeitet gerade."),
      W("Ich gang go schaffe.", "Ich gehe arbeiten."),
    ],
    lesson: "verb-frame",
    listen: { word: "bi am schaffe", means: "arbeite gerade" },
  },
  {
    id: "going-shopping",
    about: { topic: "go-cho-infinitive" },
    right: L("shopping", 7),
    wrong: [
      W("Ich bi schnäll go poschte.", "Ich war schnell einkaufen."),
      W("Mir gönd schnäll go poschte.", "Wir gehen schnell einkaufen."),
      W("Ich gang schnäll hei.", "Ich gehe schnell nach Hause."),
    ],
    lesson: "verb-frame",
    listen: { word: "gang … go poschte", means: "gehe einkaufen" },
  },
  {
    id: "come-eat",
    about: { topic: "go-cho-infinitive" },
    right: L("meals", 9),
    wrong: [
      W("Gönd Sie go ässe.", "Gehen Sie essen."),
      W("Händ Sie scho gesse?", "Haben Sie schon gegessen?"),
      W("Chömed Sie cho hälfe.", "Kommen Sie helfen."),
    ],
    lesson: "verb-frame",
    listen: { word: "Chömed … cho", means: "Kommen … (her)" },
  },
  {
    id: "come-help",
    about: { topic: "go-cho-infinitive" },
    right: X("go-cho-infinitive", 1),
    wrong: [
      W("Gaasch go hälfe?", "Gehst du helfen?"),
      W("Chunnsch morn cho hälfe?", "Kommst du morgen helfen?"),
      W("Chunnsch cho ässe?", "Kommst du essen?"),
    ],
    lesson: "verb-frame",
    listen: { word: "Chunnsch cho", means: "Kommst du … (her)" },
  },
  {
    id: "child-cried",
    about: { topic: "articles" },
    right: L("school-parents", 3),
    wrong: [
      W("D Chind händ hüt ächli gweint.", "Die Kinder haben heute ein bisschen geweint."),
      W("S Chind hät hüt vill gweint.", "Das Kind hat heute viel geweint."),
      W("S Chind hät hüt ächli glachet.", "Das Kind hat heute ein bisschen gelacht."),
    ],
    lesson: "person",
    listen: { word: "S Chind hät", means: "Das Kind hat" },
  },
  {
    id: "meiers-room",
    about: { topic: "possessive-dative" },
    right: L("visitors", 2),
    wrong: [
      W("De Herr Meier isch dört äne i sim Zimmer.", "Herr Meier ist dort drüben in seinem Zimmer."),
      W("S Zimmer dört äne isch nöd em Herr Meier sis.", "Das Zimmer dort drüben ist nicht das von Herrn Meier."),
      W("Em Herr Meier sis Zimmer isch nöd dört äne.", "Herrn Meiers Zimmer ist nicht dort drüben."),
    ],
    lesson: "whose",
    listen: { word: "Em Herr Meier sis", means: "Herrn Meiers" },
  },
  {
    id: "annas-sister",
    about: { topic: "possessive-dative" },
    right: L("visitors", 7),
    wrong: [
      W("D Anna und ihri Schwöschter chömed au no.", "Anna und ihre Schwester kommen auch noch."),
      W("D Anna chunt au no, ihri Schwöschter nöd.", "Anna kommt auch noch, ihre Schwester nicht."),
      W("D Anna chunt au no zu ihrere Schwöschter.", "Anna kommt auch noch zu ihrer Schwester."),
    ],
    lesson: "whose",
    listen: { word: "De Anna ihri", means: "Annas" },
  },
  {
    id: "stay-on-line",
    about: { topic: "imperative" },
    right: L("appointment", 16),
    wrong: [
      W("Blib churz dra.", "Bleib kurz dran."),
      W("Ich blibe churz dra.", "Ich bleibe kurz dran."),
      W("Lüüted Sie spööter aa.", "Rufen Sie später an."),
    ],
    lesson: "person",
    listen: { word: "Blibed Sie", means: "Bleiben Sie" },
  },
  {
    id: "breathe-in",
    about: { topic: "imperative" },
    right: L("doctor", 11),
    wrong: [
      W("Atme tüüf ii.", "Atme tief ein."),
      W("Atmed Sie tüüf uus.", "Atmen Sie tief aus."),
      W("Ich atme tüüf ii.", "Ich atme tief ein."),
    ],
    lesson: "person",
    listen: { word: "Atmed Sie", means: "Atmen Sie" },
  },
  {
    id: "spoonfuls",
    about: { topic: "diminutive-li" },
    right: L("meals", 14),
    wrong: [
      W("Nur en Löffel?", "Nur einen Löffel?"),
      W("Nur es paar Stückli?", "Nur ein paar Stückchen?"),
      W("Nur ächli Brot?", "Nur ein bisschen Brot?"),
    ],
    lesson: "small-word",
    listen: { word: "Löffeli", means: "Löffelchen" },
  },
  {
    id: "where-change",
    about: { topic: "question-words" },
    right: L("tram", 19),
    wrong: [
      W("Wänn mues ich umstiege?", "Wann muss ich umsteigen?"),
      W("Mues ich umstiege?", "Muss ich umsteigen?"),
      W("Wo mues ich usstiege?", "Wo muss ich aussteigen?"),
    ],
    lesson: "question-word",
    listen: { word: "Wo", means: "Wo" },
  },
  {
    id: "when-rubbish",
    about: { topic: "question-words" },
    right: X("question-words", 0),
    wrong: [
      W("Wer holt de Güsel?", "Wer holt den Abfall?"),
      W("Wänn isch d Abfuhr gsi?", "Wann war die Abfuhr?"),
      W("Chunt d Abfuhr hüt?", "Kommt die Abfuhr heute?"),
    ],
    lesson: "question-word",
    listen: { word: "Wänn", means: "Wann" },
  },
  {
    id: "another-coffee",
    about: { topic: "indefinite-article" },
    right: L("restaurant", 4),
    wrong: [
      L("restaurant", 14),
      W("Händ Sie no Kafi?", "Haben Sie noch Kaffee?"),
      W("Wänd Sie kei Kafi?", "Möchten Sie keinen Kaffee?"),
    ],
    lesson: "offer",
    listen: { word: "en Kafi", means: "einen Kaffee" },
  },
  {
    id: "not-any-more",
    about: { word: "nüme" },
    right: L("at-work", 19),
    wrong: [
      W("Das schaff ich hüt nöd.", "Das schaffe ich heute nicht."),
      W("Das schaff ich hüt no.", "Das schaffe ich heute noch."),
      W("Das schaff ich morn.", "Das schaffe ich morgen."),
    ],
    lesson: "small-word",
    listen: { word: "nüme", means: "nicht mehr" },
  },
  {
    id: "still-open",
    about: { word: "nüme" },
    right: L("shopping", 4),
    wrong: [
      W("Mir händ das grad no.", "Wir haben das gerade noch."),
      W("Mir händ das nie ghaa.", "Wir hatten das nie."),
      W("Ich ha das grad nüme.", "Ich habe das gerade nicht mehr."),
    ],
    lesson: "small-word",
    listen: { word: "nüme", means: "nicht mehr" },
  },
  {
    id: "like-a-coffee",
    about: { topic: "subjunctive" },
    right: X("subjunctive", 0),
    wrong: [
      W("Ich ha gern Kafi.", "Ich mag Kaffee."),
      W("Ich ha es Kafi gha.", "Ich hatte einen Kaffee."),
      W("Er hett gern es Kafi.", "Er hätte gern einen Kaffee."),
    ],
    lesson: "wish",
    listen: { word: "hett", means: "hätte" },
  },
  {
    id: "could-you-help",
    about: { topic: "subjunctive" },
    right: X("subjunctive", 1),
    wrong: [
      W("Händ Sie mir ghulfe?", "Haben Sie mir geholfen?"),
      W("Chönnted Sie ihm hälfe?", "Könnten Sie ihm helfen?"),
      W("Mues ich Ihne hälfe?", "Muss ich Ihnen helfen?"),
    ],
    lesson: "wish",
    listen: { word: "Chönnted Sie", means: "Könnten Sie" },
  },
  {
    id: "would-come",
    about: { topic: "subjunctive" },
    right: X("subjunctive", 2),
    wrong: [
      W("Ich chume, wänn ich Ziit ha.", "Ich komme, wenn ich Zeit habe."),
      W("Ich bi cho, will ich Ziit gha ha.", "Ich bin gekommen, weil ich Zeit hatte."),
      W("Ich chume nöd, will ich kei Ziit ha.", "Ich komme nicht, weil ich keine Zeit habe."),
    ],
    lesson: "wish",
    listen: { word: "würd … hett", means: "würde … hätte" },
  },
  {
    id: "would-be-nice",
    about: { topic: "subjunctive" },
    right: W("Das wär schön.", "Das wäre schön."),
    wrong: [
      W("Das isch schön.", "Das ist schön."),
      W("Das isch schön gsi.", "Das war schön."),
      W("Das wär nöd schön.", "Das wäre nicht schön."),
    ],
    lesson: "wish",
    listen: { word: "wär", means: "wäre" },
  },
  {
    id: "should-sleep",
    about: { topic: "subjunctive" },
    right: W("Du söttsch meh schlafe.", "Du solltest mehr schlafen."),
    wrong: [
      W("Du schlafsch meh.", "Du schläfst mehr."),
      W("Du häsch meh gschlafe.", "Du hast mehr geschlafen."),
      W("Ich sött meh schlafe.", "Ich sollte mehr schlafen."),
    ],
    lesson: "wish",
    listen: { word: "söttsch", means: "solltest" },
  },
  {
    id: "would-like-to-come",
    about: { topic: "subjunctive" },
    right: W("Si wett gern cho.", "Sie möchte gern kommen."),
    wrong: [
      W("Si chunt gern.", "Sie kommt gern."),
      W("Si isch gern cho.", "Sie ist gern gekommen."),
      W("Er wett gern cho.", "Er möchte gern kommen."),
    ],
    lesson: "wish",
    listen: { word: "wett", means: "möchte" },
  },
  {
    id: "if-i-were-you",
    about: { topic: "subjunctive" },
    right: W("Wänn ich du wär, würd ich warte.", "Wenn ich du wäre, würde ich warten."),
    wrong: [
      W("Wänn du wartisch, warte ich au.", "Wenn du wartest, warte ich auch."),
      W("Ich würd nöd warte.", "Ich würde nicht warten."),
      W("Ich ha uf dich gwartet.", "Ich habe auf dich gewartet."),
    ],
    lesson: "wish",
    listen: { word: "wär … würd", means: "wäre … würde" },
  },
  {
    id: "would-have-been-there",
    about: { topic: "subjunctive" },
    right: W("Mir wäred gern debii gsi.", "Wir wären gern dabei gewesen."),
    wrong: [
      W("Mir sind gern debii gsi.", "Wir waren gern dabei."),
      W("Mir sind debii.", "Wir sind dabei."),
      W("Si wäred gern debii gsi.", "Sie wären gern dabei gewesen."),
    ],
    lesson: "wish",
    listen: { word: "wäred", means: "wären" },
  },
  {
    id: "would-not-have",
    about: { topic: "subjunctive" },
    right: W("Ich hett das nöd gmacht.", "Ich hätte das nicht gemacht."),
    wrong: [
      W("Er hät das nöd gmacht.", "Er hat das nicht gemacht."),
      W("Ich ha das nöd gmacht.", "Ich habe das nicht gemacht."),
      W("Ich hett das gmacht.", "Ich hätte das gemacht."),
    ],
    lesson: "wish",
    listen: { word: "hett", means: "hätte" },
  },
  {
    id: "would-not-say",
    about: { topic: "subjunctive" },
    right: W("Das würd ich nöd säge.", "Das würde ich nicht sagen."),
    wrong: [
      W("Das säg ich nöd.", "Das sage ich nicht."),
      W("Das han ich nöd gseit.", "Das habe ich nicht gesagt."),
      W("Das würd ich au säge.", "Das würde ich auch sagen."),
    ],
    lesson: "wish",
    listen: { word: "würd", means: "würde" },
  },
  {
    id: "saw-him",
    about: { topic: "pronoun-clitics" },
    right: X("pronoun-clitics", 0),
    wrong: [
      W("Ich han si geschter gsee.", "Ich habe sie gestern gesehen."),
      W("Er hät mich geschter gsee.", "Er hat mich gestern gesehen."),
      W("Ich han en geschter nöd gsee.", "Ich habe ihn gestern nicht gesehen."),
    ],
    lesson: "clitic",
    listen: { word: "en", means: "ihn" },
  },
  {
    id: "tell-him",
    about: { topic: "pronoun-clitics" },
    right: X("pronoun-clitics", 1),
    wrong: [
      W("Säg ere, si söll cho.", "Sag ihr, sie soll kommen."),
      W("Säg em, er söll nöd cho.", "Sag ihm, er soll nicht kommen."),
      W("Er seit, ich söll cho.", "Er sagt, ich soll kommen."),
    ],
    lesson: "clitic",
    listen: { word: "em", means: "ihm" },
  },
  {
    id: "how-is-she",
    about: { topic: "pronoun-clitics" },
    right: X("pronoun-clitics", 2),
    wrong: [
      W("Wie gaht s em?", "Wie geht es ihm?"),
      W("Wie gaht s dir?", "Wie geht es dir?"),
      W("Wie gaht s Ihne?", "Wie geht es Ihnen?"),
    ],
    lesson: "clitic",
    listen: { word: "ere", means: "ihr" },
  },
  {
    id: "bring-him-book",
    about: { topic: "pronoun-clitics" },
    right: W("Ich bring em s Buech.", "Ich bringe ihm das Buch."),
    wrong: [
      W("Ich bring ere s Buech.", "Ich bringe ihr das Buch."),
      W("Er bringt mer s Buech.", "Er bringt mir das Buch."),
      W("Ich bring s Buech hei.", "Ich bringe das Buch nach Hause."),
    ],
    lesson: "clitic",
    listen: { word: "em", means: "ihm" },
  },
  {
    id: "found-it",
    about: { topic: "pronoun-clitics" },
    right: W("Häsch s gfunde?", "Hast du es gefunden?"),
    wrong: [
      W("Häsch en gfunde?", "Hast du ihn gefunden?"),
      W("Häsch si gfunde?", "Hast du sie gefunden?"),
      W("Hät er s gfunde?", "Hat er es gefunden?"),
    ],
    lesson: "clitic",
    listen: { word: "s", means: "es" },
  },
  {
    id: "call-you",
    about: { topic: "pronoun-clitics" },
    right: W("Ich lüüt der spööter aa.", "Ich rufe dich später an."),
    wrong: [
      W("Du lüütsch mer spööter aa.", "Du rufst mich später an."),
      W("Ich lüüt em spööter aa.", "Ich rufe ihn später an."),
      W("Ich lüüt ere spööter aa.", "Ich rufe sie später an."),
    ],
    lesson: "clitic",
    listen: { word: "der", means: "dir (dich)" },
  },
  {
    id: "help-me",
    about: { topic: "pronoun-clitics" },
    right: W("Chasch mer hälfe?", "Kannst du mir helfen?"),
    wrong: [
      W("Chasch em hälfe?", "Kannst du ihm helfen?"),
      W("Chasch ere hälfe?", "Kannst du ihr helfen?"),
      W("Chan ich der hälfe?", "Kann ich dir helfen?"),
    ],
    lesson: "clitic",
    listen: { word: "mer", means: "mir" },
  },
  {
    id: "gift-for-her",
    about: { topic: "pronoun-clitics" },
    right: W("Mir händ ere es Gschänk brocht.", "Wir haben ihr ein Geschenk gebracht."),
    wrong: [
      W("Mir händ em es Gschänk brocht.", "Wir haben ihm ein Geschenk gebracht."),
      W("Si hät eus es Gschänk brocht.", "Sie hat uns ein Geschenk gebracht."),
      W("Mir händ es Gschänk übercho.", "Wir haben ein Geschenk bekommen."),
    ],
    lesson: "clitic",
    listen: { word: "ere", means: "ihr" },
  },
  {
    id: "told-him-so",
    about: { topic: "pronoun-clitics" },
    right: W("Ich ha s em gseit.", "Ich habe es ihm gesagt."),
    wrong: [
      W("Ich ha s ere gseit.", "Ich habe es ihr gesagt."),
      W("Er hät s mer gseit.", "Er hat es mir gesagt."),
      W("Ich ha s em nöd gseit.", "Ich habe es ihm nicht gesagt."),
    ],
    lesson: "clitic",
    listen: { word: "s em", means: "es ihm" },
  },
  {
    id: "take-him-along",
    about: { topic: "pronoun-clitics" },
    right: W("Nimmsch en mit?", "Nimmst du ihn mit?"),
    wrong: [
      W("Nimmsch si mit?", "Nimmst du sie mit?"),
      W("Nimmsch mich mit?", "Nimmst du mich mit?"),
      W("Nimmsch s mit?", "Nimmst du es mit?"),
    ],
    lesson: "clitic",
    listen: { word: "en", means: "ihn" },
  },
  {
    id: "had-no-time",
    about: { topic: "participles" },
    right: X("participles", 0),
    wrong: [
      W("Ich ha kei Ziit.", "Ich habe keine Zeit."),
      W("Ich ha Ziit gha.", "Ich hatte Zeit."),
      W("Mir händ kei Ziit gha.", "Wir hatten keine Zeit."),
    ],
    lesson: "past",
    listen: { word: "gha", means: "gehabt" },
  },
  {
    id: "came-yesterday",
    about: { topic: "participles" },
    right: X("participles", 1),
    wrong: [
      W("Er chunt morn.", "Er kommt morgen."),
      W("Er isch geschter gange.", "Er ist gestern gegangen."),
      W("Si isch geschter cho.", "Sie ist gestern gekommen."),
    ],
    lesson: "past",
    listen: { word: "cho", means: "gekommen" },
  },
  {
    id: "bought-ticket",
    about: { topic: "participles" },
    right: X("participles", 2),
    wrong: [
      W("Chaufsch s Billett?", "Kaufst du die Fahrkarte?"),
      W("Häsch s Billett scho gfunde?", "Hast du die Fahrkarte schon gefunden?"),
      W("Han ich s Billett scho kauft?", "Habe ich die Fahrkarte schon gekauft?"),
    ],
    lesson: "past",
    listen: { word: "kauft", means: "gekauft" },
  },
  {
    id: "ate-well",
    about: { topic: "participles" },
    right: W("Mir händ guet gässe.", "Wir haben gut gegessen."),
    wrong: [
      W("Mir ässed guet.", "Wir essen gut."),
      W("Mir händ guet trunke.", "Wir haben gut getrunken."),
      W("Si händ guet gässe.", "Sie haben gut gegessen."),
    ],
    lesson: "past",
    listen: { word: "gässe", means: "gegessen" },
  },
  {
    id: "was-tired",
    about: { topic: "participles" },
    right: W("Ich bi müed gsi.", "Ich war müde."),
    wrong: [
      W("Ich bi müed.", "Ich bin müde."),
      W("Du bisch müed gsi.", "Du warst müde."),
      W("Ich bi nöd müed gsi.", "Ich war nicht müde."),
    ],
    lesson: "past",
    listen: { word: "gsi", means: "gewesen" },
  },
  {
    id: "drank-something",
    about: { topic: "participles" },
    right: W("Hät er öppis trunke?", "Hat er etwas getrunken?"),
    wrong: [
      W("Trinkt er öppis?", "Trinkt er etwas?"),
      W("Hät er öppis gässe?", "Hat er etwas gegessen?"),
      W("Hät si öppis trunke?", "Hat sie etwas getrunken?"),
    ],
    lesson: "past",
    listen: { word: "trunke", means: "getrunken" },
  },
  {
    id: "went-to-bern",
    about: { topic: "participles" },
    right: W("Si sind uf Bern gange.", "Sie sind nach Bern gegangen."),
    wrong: [
      W("Si gönd uf Bern.", "Sie gehen nach Bern."),
      W("Si sind vo Bern cho.", "Sie sind aus Bern gekommen."),
      W("Mir sind uf Bern gange.", "Wir sind nach Bern gegangen."),
    ],
    lesson: "past",
    listen: { word: "gange", means: "gegangen" },
  },
  {
    id: "did-laundry",
    about: { topic: "participles" },
    right: W("Ich ha d Wösch gmacht.", "Ich habe die Wäsche gemacht."),
    wrong: [
      W("Ich mach d Wösch.", "Ich mache die Wäsche."),
      W("Du häsch d Wösch gmacht.", "Du hast die Wäsche gemacht."),
      W("Ich ha d Wösch nöd gmacht.", "Ich habe die Wäsche nicht gemacht."),
    ],
    lesson: "past",
    listen: { word: "gmacht", means: "gemacht" },
  },
  {
    id: "did-she-see",
    about: { topic: "participles" },
    right: W("Hät si dich gsee?", "Hat sie dich gesehen?"),
    wrong: [
      W("Häsch si gsee?", "Hast du sie gesehen?"),
      W("Hät si dich ghört?", "Hat sie dich gehört?"),
      W("Hät si dich nöd gsee?", "Hat sie dich nicht gesehen?"),
    ],
    lesson: "past",
    listen: { word: "gsee", means: "gesehen" },
  },
  {
    id: "stayed-home",
    about: { topic: "participles" },
    right: W("Si isch dihei blibe.", "Sie ist zu Hause geblieben."),
    wrong: [
      W("Si isch nöd dihei blibe.", "Sie ist nicht zu Hause geblieben."),
      W("Si isch hei gange.", "Sie ist nach Hause gegangen."),
      W("Er isch dihei blibe.", "Er ist zu Hause geblieben."),
    ],
    lesson: "past",
    listen: { word: "blibe", means: "geblieben" },
  },
  {
    id: "could-not-come",
    about: { topic: "verb-order" },
    right: X("verb-order", 0),
    wrong: [
      W("Ich cha nöd cho.", "Ich kann nicht kommen."),
      W("Ich ha nöd wele cho.", "Ich habe nicht kommen wollen."),
      W("Ich ha chönne cho.", "Ich habe kommen können."),
    ],
    lesson: "modal-past",
    listen: { word: "chönne cho", means: "kommen können" },
  },
  {
    id: "had-to-work",
    about: { topic: "verb-order" },
    right: X("verb-order", 1),
    wrong: [
      W("Si mues schaffe.", "Sie muss arbeiten."),
      W("Si hät nöd müesse schaffe.", "Sie hat nicht arbeiten müssen."),
      W("Si hät wele schaffe.", "Sie hat arbeiten wollen."),
    ],
    lesson: "modal-past",
    listen: { word: "müesse schaffe", means: "arbeiten müssen" },
  },
  {
    id: "had-bike-fixed",
    about: { topic: "verb-order" },
    right: X("verb-order", 2),
    wrong: [
      W("Mir händ s Velo gflickt.", "Wir haben das Fahrrad geflickt."),
      W("Mir lönd s Velo flicke.", "Wir lassen das Fahrrad flicken."),
      W("Mir händ s Velo nöd lah flicke.", "Wir haben das Fahrrad nicht flicken lassen."),
    ],
    lesson: "modal-past",
    listen: { word: "lah flicke", means: "flicken lassen" },
  },
  {
    id: "was-not-allowed",
    about: { topic: "verb-order" },
    right: W("Er hät nöd dörfe cho.", "Er hat nicht kommen dürfen."),
    wrong: [
      W("Er darf nöd cho.", "Er darf nicht kommen."),
      W("Er hät nöd wele cho.", "Er hat nicht kommen wollen."),
      W("Er hät nöd müesse cho.", "Er hat nicht kommen müssen."),
    ],
    lesson: "modal-past",
    listen: { word: "dörfe cho", means: "kommen dürfen" },
  },
  {
    id: "had-to-wait",
    about: { topic: "verb-order" },
    right: W("Mir händ lang müesse warte.", "Wir haben lange warten müssen."),
    wrong: [
      W("Mir müend lang warte.", "Wir müssen lange warten."),
      W("Mir händ nöd lang müesse warte.", "Wir haben nicht lange warten müssen."),
      W("Si händ lang müesse warte.", "Sie haben lange warten müssen."),
    ],
    lesson: "modal-past",
    listen: { word: "müesse warte", means: "warten müssen" },
  },
  {
    id: "could-not-find",
    about: { topic: "verb-order" },
    right: W("Ich ha s nöd chönne finde.", "Ich habe es nicht finden können."),
    wrong: [
      W("Ich cha s nöd finde.", "Ich kann es nicht finden."),
      W("Ich ha s gfunde.", "Ich habe es gefunden."),
      W("Du häsch s nöd chönne finde.", "Du hast es nicht finden können."),
    ],
    lesson: "modal-past",
    listen: { word: "chönne finde", means: "finden können" },
  },
  {
    id: "left-car",
    about: { topic: "verb-order" },
    right: W("Si hät s Auto lah stah.", "Sie hat das Auto stehen lassen."),
    wrong: [
      W("Si hät s Auto nöd lah stah.", "Sie hat das Auto nicht stehen lassen."),
      W("Si hät s Auto parkiert.", "Sie hat das Auto geparkt."),
      W("Er hät s Auto lah stah.", "Er hat das Auto stehen lassen."),
    ],
    lesson: "modal-past",
    listen: { word: "lah stah", means: "stehen lassen" },
  },
  {
    id: "had-to-pay",
    about: { topic: "verb-order" },
    right: W("Häsch müesse zahle?", "Hast du zahlen müssen?"),
    wrong: [
      W("Muesch zahle?", "Musst du zahlen?"),
      W("Häsch zahlt?", "Hast du gezahlt?"),
      W("Han ich müesse zahle?", "Habe ich zahlen müssen?"),
    ],
    lesson: "modal-past",
    listen: { word: "müesse zahle", means: "zahlen müssen" },
  },
  {
    id: "did-not-want-to-disturb",
    about: { topic: "verb-order" },
    right: W("Mir händ nöd wele störe.", "Wir haben nicht stören wollen."),
    wrong: [
      W("Mir wänd nöd störe.", "Wir wollen nicht stören."),
      W("Mir händ gstört.", "Wir haben gestört."),
      W("Ich ha nöd wele störe.", "Ich habe nicht stören wollen."),
    ],
    lesson: "modal-past",
    listen: { word: "wele störe", means: "stören wollen" },
  },
  {
    id: "kept-waiting",
    about: { topic: "verb-order" },
    right: W("De Dokter hät mich lah warte.", "Der Arzt hat mich warten lassen."),
    wrong: [
      W("De Dokter hät gwartet.", "Der Arzt hat gewartet."),
      W("Ich ha de Dokter lah warte.", "Ich habe den Arzt warten lassen."),
      W("De Dokter hät mich nöd lah warte.", "Der Arzt hat mich nicht warten lassen."),
    ],
    lesson: "modal-past",
    listen: { word: "lah warte", means: "warten lassen" },
  },
  {
    id: "come-in",
    about: { topic: "directions" },
    right: X("directions", 0),
    wrong: [
      W("Gönd Sie use!", "Gehen Sie hinaus!"),
      W("Chömed Sie abe!", "Kommen Sie herunter!"),
      W("Chömed Sie ufe!", "Kommen Sie herauf!"),
    ],
    lesson: "direction",
    listen: { word: "ine", means: "herein" },
  },
  {
    id: "going-down",
    about: { topic: "directions" },
    right: X("directions", 1),
    wrong: [
      W("Ich gang schnäll ufe.", "Ich gehe schnell hinauf."),
      W("Ich gang schnäll use.", "Ich gehe schnell hinaus."),
      W("Ich gang schnäll ume.", "Ich gehe schnell hinüber."),
    ],
    lesson: "direction",
    listen: { word: "abe", means: "hinunter" },
  },
  {
    id: "rubbish-out",
    about: { topic: "directions" },
    right: X("directions", 2),
    wrong: [
      W("Bringsch de Güsel abe?", "Bringst du den Abfall hinunter?"),
      W("Nimmsch de Güsel ine?", "Nimmst du den Abfall herein?"),
      W("Bringsch de Güsel ufe?", "Bringst du den Abfall hinauf?"),
    ],
    lesson: "direction",
    listen: { word: "use", means: "hinaus" },
  },
  {
    id: "coming-up",
    about: { topic: "directions" },
    right: W("Chunnsch au ufe?", "Kommst du auch herauf?"),
    wrong: [
      W("Chunnsch au abe?", "Kommst du auch herunter?"),
      W("Chunnsch au ine?", "Kommst du auch herein?"),
      W("Chunnsch au use?", "Kommst du auch heraus?"),
    ],
    lesson: "direction",
    listen: { word: "ufe", means: "herauf" },
  },
  {
    id: "run-across",
    about: { topic: "directions" },
    right: W("Ich spring schnäll ume.", "Ich renne schnell hinüber."),
    wrong: [
      W("Ich spring schnäll zrugg.", "Ich renne schnell zurück."),
      W("Ich spring schnäll abe.", "Ich renne schnell hinunter."),
      W("Ich spring schnäll use.", "Ich renne schnell hinaus."),
    ],
    lesson: "direction",
    listen: { word: "ume", means: "hinüber" },
  },
  {
    id: "laundry-in",
    about: { topic: "directions" },
    right: W("Nimm d Wösch ine, es rägnet.", "Nimm die Wäsche herein, es regnet."),
    wrong: [
      W("Nimm d Wösch abe, es rägnet.", "Nimm die Wäsche herunter, es regnet."),
      W("Bring d Wösch ufe, es rägnet.", "Bring die Wäsche hinauf, es regnet."),
      W("Häng d Wösch use, es rägnet.", "Häng die Wäsche hinaus, es regnet."),
    ],
    lesson: "direction",
    listen: { word: "ine", means: "herein" },
  },
  {
    id: "just-went-out",
    about: { topic: "directions" },
    right: W("Si isch grad use gange.", "Sie ist gerade hinausgegangen."),
    wrong: [
      W("Si isch grad ine cho.", "Sie ist gerade hereingekommen."),
      W("Si isch grad abe gange.", "Sie ist gerade hinuntergegangen."),
      W("Er isch grad use gange.", "Er ist gerade hinausgegangen."),
    ],
    lesson: "direction",
    listen: { word: "use", means: "hinaus" },
  },
  {
    id: "basket-up",
    about: { topic: "directions" },
    right: W("Chasch mer de Chorb ufe bringe?", "Kannst du mir den Korb heraufbringen?"),
    wrong: [
      W("Chasch mer de Chorb abe bringe?", "Kannst du mir den Korb herunterbringen?"),
      W("Chasch em de Chorb ufe bringe?", "Kannst du ihm den Korb hinaufbringen?"),
      W("Chasch mer de Chorb ine bringe?", "Kannst du mir den Korb hereinbringen?"),
    ],
    lesson: "direction",
    listen: { word: "ufe", means: "herauf" },
  },
  {
    id: "look-out",
    about: { topic: "directions" },
    right: W("Lueg emal use!", "Schau mal hinaus!"),
    wrong: [
      W("Lueg emal ine!", "Schau mal hinein!"),
      W("Lueg emal abe!", "Schau mal hinunter!"),
      W("Lueg emal ufe!", "Schau mal hinauf!"),
    ],
    lesson: "direction",
    listen: { word: "use", means: "hinaus" },
  },
  {
    id: "dog-out",
    about: { topic: "directions" },
    right: W("De Hund wott use.", "Der Hund will hinaus."),
    wrong: [
      W("De Hund wott ine.", "Der Hund will herein."),
      W("De Hund wott ufe.", "Der Hund will hinauf."),
      W("De Hund wott abe.", "Der Hund will hinunter."),
    ],
    lesson: "direction",
    listen: { word: "use", means: "hinaus" },
  },
  {
    id: "this-is-anna",
    about: { topic: "names-article" },
    right: X("names-article", 0),
    wrong: [
      W("Das isch de Anna ihre Maa.", "Das ist Annas Mann."),
      W("Das isch nöd d Anna.", "Das ist nicht Anna."),
      W("Das isch für d Anna.", "Das ist für Anna."),
    ],
    lesson: "name-role",
    listen: { word: "d Anna", means: "Anna" },
  },
  {
    id: "seen-peter",
    about: { topic: "names-article" },
    right: X("names-article", 1),
    wrong: [
      W("Hät de Peter dich gsee?", "Hat Peter dich gesehen?"),
      W("Häsch em Peter gschribe?", "Hast du Peter geschrieben?"),
      W("Häsch de Peter nöd gsee?", "Hast du Peter nicht gesehen?"),
    ],
    lesson: "name-role",
    listen: { word: "de Peter", means: "Peter (wen?)" },
  },
  {
    id: "tell-luca",
    about: { topic: "names-article" },
    right: X("names-article", 2),
    wrong: [
      W("De Luca seit s mir.", "Luca sagt es mir."),
      W("Ich säg s em Luca nöd.", "Ich sage es Luca nicht."),
      W("Ich frög de Luca.", "Ich frage Luca."),
    ],
    lesson: "name-role",
    listen: { word: "em Luca", means: "Luca (wem?)" },
  },
  {
    id: "bring-anna",
    about: { topic: "names-article" },
    right: W("Ich bring s de Anna.", "Ich bringe es Anna."),
    wrong: [
      W("D Anna bringt s mir.", "Anna bringt es mir."),
      W("Ich bring d Anna hei.", "Ich bringe Anna nach Hause."),
      W("Ich bring s de Anna nöd.", "Ich bringe es Anna nicht."),
    ],
    lesson: "name-role",
    listen: { word: "de Anna", means: "Anna (wem?)" },
  },
  {
    id: "anna-called-peter",
    about: { topic: "names-article" },
    right: W("Hät d Anna em Peter aaglüütet?", "Hat Anna Peter angerufen?"),
    wrong: [
      W("Hät de Peter de Anna aaglüütet?", "Hat Peter Anna angerufen?"),
      W("Hät d Anna em Peter gschribe?", "Hat Anna Peter geschrieben?"),
      W("Hät d Anna de Peter gsee?", "Hat Anna Peter gesehen?"),
    ],
    lesson: "name-role",
    listen: { word: "d Anna … em Peter", means: "Anna (wer?) … Peter (wem?)" },
  },
  {
    id: "luca-helps-anna",
    about: { topic: "names-article" },
    right: W("De Luca hilft de Anna.", "Luca hilft Anna."),
    wrong: [
      W("D Anna hilft em Luca.", "Anna hilft Luca."),
      W("De Luca hät de Anna ghulfe.", "Luca hat Anna geholfen."),
      W("D Anna und de Luca hälfed.", "Anna und Luca helfen."),
    ],
    lesson: "name-role",
    listen: { word: "De Luca … de Anna", means: "Luca (wer?) … Anna (wem?)" },
  },
  {
    id: "anna-coming",
    about: { topic: "names-article" },
    right: W("Chunt d Anna morn?", "Kommt Anna morgen?"),
    wrong: [
      W("Chunnsch morn zu de Anna?", "Kommst du morgen zu Anna?"),
      W("Chunt d Anna morn nöd?", "Kommt Anna morgen nicht?"),
      W("Isch d Anna geschter cho?", "Ist Anna gestern gekommen?"),
    ],
    lesson: "name-role",
    listen: { word: "d Anna", means: "Anna" },
  },
  {
    id: "invited-peter",
    about: { topic: "names-article" },
    right: W("Mir händ de Peter iiglade.", "Wir haben Peter eingeladen."),
    wrong: [
      W("De Peter hät eus iiglade.", "Peter hat uns eingeladen."),
      W("Mir sind bim Peter gsi.", "Wir waren bei Peter."),
      W("Mir händ em Peter gschribe.", "Wir haben Peter geschrieben."),
    ],
    lesson: "name-role",
    listen: { word: "de Peter", means: "Peter (wen?)" },
  },
  {
    id: "show-peter",
    about: { topic: "names-article" },
    right: W("Zeig s em Peter.", "Zeig es Peter."),
    wrong: [
      W("De Peter söll s zeige.", "Peter soll es zeigen."),
      W("Frög de Peter.", "Frag Peter."),
      W("Zeig s em Peter nöd.", "Zeig es Peter nicht."),
    ],
    lesson: "name-role",
    listen: { word: "em Peter", means: "Peter (wem?)" },
  },
  {
    id: "anna-waits-for-luca",
    about: { topic: "names-article" },
    right: W("D Anna wartet uf de Luca.", "Anna wartet auf Luca."),
    wrong: [
      W("De Luca wartet uf d Anna.", "Luca wartet auf Anna."),
      W("D Anna und de Luca warted.", "Anna und Luca warten."),
      W("D Anna wartet nöd uf de Luca.", "Anna wartet nicht auf Luca."),
    ],
    lesson: "name-role",
    listen: { word: "D Anna", means: "Anna (wer?)" },
  },
  {
    id: "how-long",
    about: { topic: "question-words" },
    right: W("Wie lang dauret das?", "Wie lange dauert das?"),
    wrong: [
      W("Wänn fangt das aa?", "Wann fängt das an?"),
      W("Wo isch das?", "Wo ist das?"),
      W("Was chostet das?", "Was kostet das?"),
    ],
    lesson: "question-word",
    listen: { word: "Wie lang", means: "Wie lange" },
  },
  {
    id: "who-was-it",
    about: { topic: "question-words" },
    right: W("Wer isch das gsi?", "Wer war das?"),
    wrong: [
      W("Was isch das gsi?", "Was war das?"),
      W("Wo isch das gsi?", "Wo war das?"),
      W("Wänn isch das gsi?", "Wann war das?"),
    ],
    lesson: "question-word",
    listen: { word: "Wer", means: "Wer" },
  },
  {
    id: "we-come-later",
    about: { topic: "unified-plural" },
    right: W("Mir chömed spööter.", "Wir kommen später."),
    wrong: [
      W("Si chömed spööter.", "Sie kommen später."),
      W("Ihr chömed spööter.", "Ihr kommt später."),
      W("Mir sind spööter cho.", "Wir sind später gekommen."),
    ],
    lesson: "person",
    listen: { word: "Mir", means: "wir" },
  },
  {
    id: "you-hungry",
    about: { topic: "unified-plural" },
    right: W("Ihr händ Hunger.", "Ihr habt Hunger."),
    wrong: [
      W("Mir händ Hunger.", "Wir haben Hunger."),
      W("Si händ Hunger.", "Sie haben Hunger."),
      W("Du häsch Hunger.", "Du hast Hunger."),
    ],
    lesson: "person",
    listen: { word: "Ihr händ", means: "Ihr habt" },
  },
  {
    id: "they-live",
    about: { topic: "unified-plural" },
    right: W("Si wohned im Chreis vier.", "Sie wohnen im Kreis vier."),
    wrong: [
      W("Mir wohned im Chreis vier.", "Wir wohnen im Kreis vier."),
      W("Ihr wohned im Chreis vier.", "Ihr wohnt im Kreis vier."),
      W("Si wohnt im Chreis vier.", "Sie wohnt im Kreis vier."),
    ],
    lesson: "person",
    listen: { word: "Si wohned", means: "Sie wohnen" },
  },
  {
    id: "we-go-home",
    about: { topic: "unified-plural" },
    right: W("Mir gönd hei.", "Wir gehen nach Hause."),
    wrong: [
      W("Ihr gönd hei.", "Ihr geht nach Hause."),
      W("Si gönd hei.", "Sie gehen nach Hause."),
      W("Ich gang hei.", "Ich gehe nach Hause."),
    ],
    lesson: "person",
    listen: { word: "Mir gönd", means: "Wir gehen" },
  },
  {
    id: "go-shopping",
    about: { topic: "go-cho-infinitive" },
    right: W("Ich gang go poschte.", "Ich gehe einkaufen."),
    wrong: [
      W("Ich bi go poschte gsi.", "Ich war einkaufen."),
      W("Mir gönd go poschte.", "Wir gehen einkaufen."),
      W("Ich gang nöd go poschte.", "Ich gehe nicht einkaufen."),
    ],
    lesson: "verb-frame",
    listen: { word: "go poschte", means: "einkaufen (gehen)" },
  },
  {
    id: "comes-to-visit",
    about: { topic: "go-cho-infinitive" },
    right: W("Si chunt eus cho bsueche.", "Sie kommt uns besuchen."),
    wrong: [
      W("Mir gönd si go bsueche.", "Wir gehen sie besuchen."),
      W("Si isch eus cho bsueche.", "Sie ist uns besuchen gekommen."),
      W("Si chunt eus nöd cho bsueche.", "Sie kommt uns nicht besuchen."),
    ],
    lesson: "verb-frame",
    listen: { word: "cho bsueche", means: "besuchen (kommen)" },
  },
  {
    id: "go-swimming",
    about: { topic: "go-cho-infinitive" },
    right: W("Mir gönd go schwümme.", "Wir gehen schwimmen."),
    wrong: [
      W("Ihr chömed cho schwümme.", "Ihr kommt schwimmen."),
      W("Mir gönd nöd go schwümme.", "Wir gehen nicht schwimmen."),
      W("Mir sind go schwümme gsi.", "Wir waren schwimmen."),
    ],
    lesson: "verb-frame",
    listen: { word: "go schwümme", means: "schwimmen (gehen)" },
  },
  {
    id: "pick-you-up",
    about: { topic: "go-cho-infinitive" },
    right: W("Ich chume dich cho abhole.", "Ich komme dich abholen."),
    wrong: [
      W("Ich gang en go abhole.", "Ich gehe ihn abholen."),
      W("Du chunnsch mich cho abhole.", "Du kommst mich abholen."),
      W("Ich bi dich cho abhole.", "Ich bin dich abholen gekommen."),
    ],
    lesson: "verb-frame",
    listen: { word: "cho abhole", means: "abholen (kommen)" },
  },
  {
    id: "goes-to-work",
    about: { topic: "go-cho-infinitive" },
    right: W("Er gaht go schaffe.", "Er geht arbeiten."),
    wrong: [
      W("Er chunt cho schaffe.", "Er kommt arbeiten."),
      W("Er isch go schaffe gsi.", "Er war arbeiten."),
      W("Si gaht go schaffe.", "Sie geht arbeiten."),
    ],
    lesson: "verb-frame",
    listen: { word: "go schaffe", means: "arbeiten (gehen)" },
  },
  {
    id: "cooking-now",
    about: { topic: "am-progressive" },
    right: W("Ich bi am choche.", "Ich koche gerade."),
    wrong: [
      W("Ich ha gchochet.", "Ich habe gekocht."),
      W("Si isch am choche.", "Sie kocht gerade."),
      W("Ich bi am ässe.", "Ich esse gerade."),
    ],
    lesson: "verb-frame",
    listen: { word: "bi am choche", means: "koche gerade" },
  },
  {
    id: "moving-house",
    about: { topic: "am-progressive" },
    right: W("Mir sind am zügle.", "Wir ziehen gerade um."),
    wrong: [
      W("Mir händ züglet.", "Wir sind umgezogen."),
      W("Si sind am zügle.", "Sie ziehen gerade um."),
      W("Mir sind nöd am zügle.", "Wir ziehen gerade nicht um."),
    ],
    lesson: "verb-frame",
    listen: { word: "am zügle", means: "ziehen gerade um" },
  },
  {
    id: "sleeping-now",
    about: { topic: "am-progressive" },
    right: W("Er isch am schlafe.", "Er schläft gerade."),
    wrong: [
      W("Er hät gschlafe.", "Er hat geschlafen."),
      W("Er isch am schaffe.", "Er arbeitet gerade."),
      W("Si isch am schlafe.", "Sie schläft gerade."),
    ],
    lesson: "verb-frame",
    listen: { word: "am schlafe", means: "schläft gerade" },
  },
  {
    id: "on-the-phone",
    about: { topic: "am-progressive" },
    right: W("Bisch am telefoniere?", "Telefonierst du gerade?"),
    wrong: [
      W("Häsch telefoniert?", "Hast du telefoniert?"),
      W("Isch si am telefoniere?", "Telefoniert sie gerade?"),
      W("Bisch am schaffe?", "Arbeitest du gerade?"),
    ],
    lesson: "verb-frame",
    listen: { word: "am telefoniere", means: "telefonierst gerade" },
  },
  {
    id: "children-playing",
    about: { topic: "am-progressive" },
    right: W("D Chind sind am spile.", "Die Kinder spielen gerade."),
    wrong: [
      W("D Chind händ gspilt.", "Die Kinder haben gespielt."),
      W("S Chind isch am spile.", "Das Kind spielt gerade."),
      W("D Chind sind am ässe.", "Die Kinder essen gerade."),
    ],
    lesson: "verb-frame",
    listen: { word: "am spile", means: "spielen gerade" },
  },
  {
    id: "eating-now",
    about: { topic: "am-progressive" },
    right: W("Si isch grad am ässe.", "Sie isst gerade."),
    wrong: [
      W("Si hät scho gässe.", "Sie hat schon gegessen."),
      W("Si isch grad am choche.", "Sie kocht gerade."),
      W("Mir sind grad am ässe.", "Wir essen gerade."),
    ],
    lesson: "verb-frame",
    listen: { word: "am ässe", means: "isst gerade" },
  },
  {
    id: "man-who-saw-me",
    about: { topic: "wo-relative" },
    right: W("Das isch de Maa, wo mich gsee hät.", "Das ist der Mann, der mich gesehen hat."),
    wrong: [
      W("Das isch de Maa, wo ich gsee ha.", "Das ist der Mann, den ich gesehen habe."),
      W("Das isch de Maa, wo si gsee hät.", "Das ist der Mann, den sie gesehen hat."),
      W("Das isch de Maa, wo dich gsee hät.", "Das ist der Mann, der dich gesehen hat."),
    ],
    lesson: "relative",
    listen: { word: "wo mich gsee hät", means: "der mich gesehen hat" },
  },
  {
    id: "woman-who-visited",
    about: { topic: "wo-relative" },
    right: W("D Frau, wo eus bsuecht hät, isch Ärztin.", "Die Frau, die uns besucht hat, ist Ärztin."),
    wrong: [
      W("D Frau, wo mir bsuecht händ, isch Ärztin.", "Die Frau, die wir besucht haben, ist Ärztin."),
      W("D Frau, wo ich bsuecht ha, isch Ärztin.", "Die Frau, die ich besucht habe, ist Ärztin."),
      W("D Frau, wo mich bsuecht hät, isch Ärztin.", "Die Frau, die mich besucht hat, ist Ärztin."),
    ],
    lesson: "relative",
    listen: { word: "wo eus bsuecht hät", means: "die uns besucht hat" },
  },
  {
    id: "book-you-gave",
    about: { topic: "wo-relative" },
    right: W("S Buech, wo du mer ggä häsch, isch guet.", "Das Buch, das du mir gegeben hast, ist gut."),
    wrong: [
      W("S Buech, wo ich der ggä ha, isch guet.", "Das Buch, das ich dir gegeben habe, ist gut."),
      W("S Buech, wo du vo mir übercho häsch, isch guet.", "Das Buch, das du von mir bekommen hast, ist gut."),
      W("S Buech, wo er der ggä hät, isch guet.", "Das Buch, das er dir gegeben hat, ist gut."),
    ],
    lesson: "relative",
    listen: { word: "wo du mer ggä häsch", means: "das du mir gegeben hast" },
  },
  {
    id: "boy-playing",
    about: { topic: "wo-relative" },
    right: W("Kännsch de Bueb, wo dört spilt?", "Kennst du den Jungen, der dort spielt?"),
    wrong: [
      W("Kännsch de Bueb, wo dört gspilt hät?", "Kennst du den Jungen, der dort gespielt hat?"),
      W("Kännt de Bueb, wo dört spilt, dich?", "Kennt der Junge, der dort spielt, dich?"),
      W("Kännsch de Bueb nöd, wo dört spilt?", "Kennst du den Jungen nicht, der dort spielt?"),
    ],
    lesson: "relative",
    listen: { word: "wo dört spilt", means: "der dort spielt" },
  },
  {
    id: "restaurant-yesterday",
    about: { topic: "wo-relative" },
    right: W("Das isch s Restaurant, wo mir geschter gsi sind.", "Das ist das Restaurant, in dem wir gestern waren."),
    wrong: [
      W("Das isch s Restaurant, wo mir morn gönd.", "Das ist das Restaurant, in das wir morgen gehen."),
      W("Das isch s Restaurant, wo du geschter gsi bisch.", "Das ist das Restaurant, in dem du gestern warst."),
      W("Das isch s Restaurant, wo si geschter gsi sind.", "Das ist das Restaurant, in dem sie gestern waren."),
    ],
    lesson: "relative",
    listen: { word: "wo mir geschter gsi sind", means: "in dem wir gestern waren" },
  },
  {
    id: "colleague-picked-up",
    about: { topic: "wo-relative" },
    right: W("Das isch de Kolleg, wo mich abgholt hät.", "Das ist der Kollege, der mich abgeholt hat."),
    wrong: [
      W("Das isch de Kolleg, wo ich abgholt ha.", "Das ist der Kollege, den ich abgeholt habe."),
      W("Das isch de Kolleg, wo dich abgholt hät.", "Das ist der Kollege, der dich abgeholt hat."),
      W("Das isch de Kolleg, wo mich abhole wott.", "Das ist der Kollege, der mich abholen will."),
    ],
    lesson: "relative",
    listen: { word: "wo mich abgholt hät", means: "der mich abgeholt hat" },
  },
  {
    id: "people-invited",
    about: { topic: "wo-relative" },
    right: W("D Lüüt, wo mir iiglade händ, chömed nöd.", "Die Leute, die wir eingeladen haben, kommen nicht."),
    wrong: [
      W("D Lüüt, wo eus iiglade händ, chömed nöd.", "Die Leute, die uns eingeladen haben, kommen nicht."),
      W("D Lüüt, wo si iiglade händ, chömed nöd.", "Die Leute, die sie eingeladen haben, kommen nicht."),
      W("D Lüüt, wo mir iilade wänd, chömed nöd.", "Die Leute, die wir einladen wollen, kommen nicht."),
    ],
    lesson: "relative",
    listen: { word: "wo mir iiglade händ", means: "die wir eingeladen haben" },
  },
  {
    id: "key-you-look-for",
    about: { topic: "wo-relative" },
    right: W("De Schlüssel, wo du suechsch, isch da.", "Der Schlüssel, den du suchst, ist hier."),
    wrong: [
      W("De Schlüssel, wo ich suech, isch da.", "Der Schlüssel, den ich suche, ist hier."),
      W("De Schlüssel, wo er suecht, isch da.", "Der Schlüssel, den er sucht, ist hier."),
      W("De Schlüssel, wo du gfunde häsch, isch da.", "Der Schlüssel, den du gefunden hast, ist hier."),
    ],
    lesson: "relative",
    listen: { word: "wo du suechsch", means: "den du suchst" },
  },
  {
    id: "peters-bike",
    about: { topic: "possessive-dative" },
    right: W("Das isch em Peter sis Velo.", "Das ist Peters Fahrrad."),
    wrong: [
      W("De Peter hät mis Velo.", "Peter hat mein Fahrrad."),
      W("Das Velo isch für de Peter.", "Das Fahrrad ist für Peter."),
      W("De Peter hät kei Velo.", "Peter hat kein Fahrrad."),
    ],
    lesson: "whose",
    listen: { word: "em Peter sis", means: "Peters" },
  },
  {
    id: "annas-husband",
    about: { topic: "possessive-dative" },
    right: W("De Anna ihre Maa isch Lehrer.", "Annas Mann ist Lehrer."),
    wrong: [
      W("D Anna isch Lehreri.", "Anna ist Lehrerin."),
      W("D Anna und ihre Maa sind Lehrer.", "Anna und ihr Mann sind Lehrer."),
      W("De Anna ihre Maa isch nöd Lehrer.", "Annas Mann ist nicht Lehrer."),
    ],
    lesson: "whose",
    listen: { word: "De Anna ihre", means: "Annas" },
  },
  {
    id: "lucas-parents",
    about: { topic: "possessive-dative" },
    right: W("Mir händ em Luca sini Eltere troffe.", "Wir haben Lucas Eltern getroffen."),
    wrong: [
      W("Mir händ de Luca und sini Eltere troffe.", "Wir haben Luca und seine Eltern getroffen."),
      W("Mir händ em Luca sini Eltere nöd troffe.", "Wir haben Lucas Eltern nicht getroffen."),
      W("Em Luca sini Eltere händ eus troffe.", "Lucas Eltern haben uns getroffen."),
    ],
    lesson: "whose",
    listen: { word: "em Luca sini", means: "Lucas" },
  },
  {
    id: "whose-phone",
    about: { topic: "possessive-dative" },
    right: W("Wäm sis Handy isch das?", "Wessen Handy ist das?"),
    wrong: [
      W("Wer hät das Handy?", "Wer hat das Handy?"),
      W("Wo isch mis Handy?", "Wo ist mein Handy?"),
      W("Isch das dis Handy?", "Ist das dein Handy?"),
    ],
    lesson: "whose",
    listen: { word: "Wäm sis", means: "Wessen" },
  },
  {
    id: "mothers-flat",
    about: { topic: "possessive-dative" },
    right: W("Das isch minere Mueter ihri Wohnig.", "Das ist die Wohnung meiner Mutter."),
    wrong: [
      W("Das isch mini Wohnig.", "Das ist meine Wohnung."),
      W("Mini Mueter wohnt bi mir.", "Meine Mutter wohnt bei mir."),
      W("Das isch nöd minere Mueter ihri Wohnig.", "Das ist nicht die Wohnung meiner Mutter."),
    ],
    lesson: "whose",
    listen: { word: "minere Mueter ihri", means: "meiner Mutter" },
  },
  {
    id: "muellers-dog",
    about: { topic: "possessive-dative" },
    right: W("Em Herr Müller sin Hund bellt.", "Herrn Müllers Hund bellt."),
    wrong: [
      W("Em Herr Müller sin Hund bellt nöd.", "Herrn Müllers Hund bellt nicht."),
      W("De Hund bellt de Herr Müller aa.", "Der Hund bellt Herrn Müller an."),
      W("De Herr Müller hät kei Hund.", "Herr Müller hat keinen Hund."),
    ],
    lesson: "whose",
    listen: { word: "Em Herr Müller sin", means: "Herrn Müllers" },
  },
  {
    id: "annas-number",
    about: { topic: "possessive-dative" },
    right: W("Häsch de Anna ihri Nummere?", "Hast du Annas Nummer?"),
    wrong: [
      W("Hät d Anna dini Nummere?", "Hat Anna deine Nummer?"),
      W("Häsch de Anna aaglüütet?", "Hast du Anna angerufen?"),
      W("Häsch mini Nummere?", "Hast du meine Nummer?"),
    ],
    lesson: "whose",
    listen: { word: "de Anna ihri", means: "Annas" },
  },
  {
    id: "neighbours-child",
    about: { topic: "possessive-dative" },
    right: W("S Chind vo de Nachbere isch chrank.", "Das Kind der Nachbarn ist krank."),
    wrong: [
      W("D Nachbere sind chrank.", "Die Nachbarn sind krank."),
      W("S Chind vo de Nachbere isch nüme chrank.", "Das Kind der Nachbarn ist nicht mehr krank."),
      W("Eusi Nachbere händ kei Chind.", "Unsere Nachbarn haben keine Kinder."),
    ],
    lesson: "whose",
    listen: { word: "vo de Nachbere", means: "der Nachbarn" },
  },
  {
    id: "take-a-seat",
    about: { topic: "imperative" },
    right: W("Nämed Sie Platz.", "Nehmen Sie Platz."),
    wrong: [
      W("Nimm Platz.", "Nimm Platz."),
      W("Ich nime Platz.", "Ich nehme Platz."),
      W("Nämed Platz.", "Nehmt Platz."),
    ],
    lesson: "person",
    listen: { word: "Nämed Sie", means: "Nehmen Sie" },
  },
  {
    id: "wait-here",
    about: { topic: "imperative" },
    right: W("Warted Sie da.", "Warten Sie hier."),
    wrong: [
      W("Wart da.", "Warte hier."),
      W("Mir warted da.", "Wir warten hier."),
      W("Warted da.", "Wartet hier."),
    ],
    lesson: "person",
    listen: { word: "Warted Sie", means: "Warten Sie" },
  },
  {
    id: "look-at-this",
    about: { topic: "imperative" },
    right: W("Lueg emal!", "Schau mal!"),
    wrong: [
      W("Lueged Sie emal!", "Schauen Sie mal!"),
      W("Lueg nöd!", "Schau nicht!"),
      W("Lueged emal!", "Schaut mal!"),
    ],
    lesson: "person",
    listen: { word: "Lueg", means: "Schau" },
  },
  {
    id: "give-me-book",
    about: { topic: "imperative" },
    right: W("Gib mer das Buech.", "Gib mir das Buch."),
    wrong: [
      W("Gänd Sie mer das Buech.", "Geben Sie mir das Buch."),
      W("Ich gib der das Buech.", "Ich gebe dir das Buch."),
      W("Gib em das Buech.", "Gib ihm das Buch."),
    ],
    lesson: "person",
    listen: { word: "Gib mer", means: "Gib mir" },
  },
  {
    id: "sit-down",
    about: { topic: "imperative" },
    right: W("Sitzed Sie ab.", "Setzen Sie sich."),
    wrong: [
      W("Sitz ab.", "Setz dich."),
      W("Mir sitzed ab.", "Wir setzen uns."),
      W("Stönd Sie uf.", "Stehen Sie auf."),
    ],
    lesson: "person",
    listen: { word: "Sitzed Sie", means: "Setzen Sie sich" },
  },
  {
    id: "close-door",
    about: { topic: "imperative" },
    right: W("Mach d Türe zue.", "Mach die Tür zu."),
    wrong: [
      W("Mached Sie d Türe zue.", "Machen Sie die Tür zu."),
      W("Mach d Türe uf.", "Mach die Tür auf."),
      W("Ich mach d Türe zue.", "Ich mache die Tür zu."),
    ],
    lesson: "person",
    listen: { word: "Mach", means: "Mach" },
  },
  {
    id: "let-me-know",
    about: { topic: "imperative" },
    right: W("Säged Sie mer Bscheid.", "Sagen Sie mir Bescheid."),
    wrong: [
      W("Säg mer Bscheid.", "Sag mir Bescheid."),
      W("Ich säg Ihne Bscheid.", "Ich sage Ihnen Bescheid."),
      W("Säged mer Bscheid.", "Sagt mir Bescheid."),
    ],
    lesson: "person",
    listen: { word: "Säged Sie", means: "Sagen Sie" },
  },
  {
    id: "a-problem",
    about: { topic: "indefinite-article" },
    right: W("Mir händ es Problem.", "Wir haben ein Problem."),
    wrong: [
      W("Mir händ kei Problem.", "Wir haben kein Problem."),
      W("Mir händ s Problem.", "Wir haben das Problem."),
      W("Si händ es Problem.", "Sie haben ein Problem."),
    ],
    lesson: "small-word",
    listen: { word: "es", means: "ein" },
  },
  {
    id: "a-flat",
    about: { topic: "indefinite-article" },
    right: W("Ich suech e Wohnig.", "Ich suche eine Wohnung."),
    wrong: [
      W("Ich suech d Wohnig.", "Ich suche die Wohnung."),
      W("Ich ha e Wohnig.", "Ich habe eine Wohnung."),
      W("Ich suech kei Wohnig.", "Ich suche keine Wohnung."),
    ],
    lesson: "small-word",
    listen: { word: "e", means: "eine" },
  },
  {
    id: "a-pen",
    about: { topic: "indefinite-article" },
    right: W("Häsch en Stift?", "Hast du einen Stift?"),
    wrong: [
      W("Häsch de Stift?", "Hast du den Stift?"),
      W("Häsch kei Stift?", "Hast du keinen Stift?"),
      W("Bruuchsch en Stift?", "Brauchst du einen Stift?"),
    ],
    lesson: "small-word",
    listen: { word: "en", means: "einen" },
  },
  {
    id: "good-idea",
    about: { topic: "indefinite-article" },
    right: W("Das isch e gueti Idee.", "Das ist eine gute Idee."),
    wrong: [
      W("Das isch kei gueti Idee.", "Das ist keine gute Idee."),
      W("Das isch d Idee.", "Das ist die Idee."),
      W("Das isch mini Idee.", "Das ist meine Idee."),
    ],
    lesson: "small-word",
    listen: { word: "e", means: "eine" },
  },
  {
    id: "a-roll",
    about: { topic: "indefinite-article" },
    right: W("Ich nime es Weggli.", "Ich nehme ein Brötchen."),
    wrong: [
      W("Ich nime s Weggli.", "Ich nehme das Brötchen."),
      W("Ich nime kei Weggli.", "Ich nehme kein Brötchen."),
      W("Ich nime zwei Weggli.", "Ich nehme zwei Brötchen."),
    ],
    lesson: "small-word",
    listen: { word: "es", means: "ein" },
  },
  {
    id: "has-a-dog",
    about: { topic: "indefinite-article" },
    right: W("Er hät en Hund.", "Er hat einen Hund."),
    wrong: [
      W("Er hät kei Hund.", "Er hat keinen Hund."),
      W("Er hät de Hund.", "Er hat den Hund."),
      W("Si hät en Hund.", "Sie hat einen Hund."),
    ],
    lesson: "small-word",
    listen: { word: "en", means: "einen" },
  },
  {
    id: "a-question",
    about: { topic: "indefinite-article" },
    right: W("Chan ich e Frag stelle?", "Kann ich eine Frage stellen?"),
    wrong: [
      W("Chasch du e Frag stelle?", "Kannst du eine Frage stellen?"),
      W("Chan ich d Frag stelle?", "Kann ich die Frage stellen?"),
      W("Chan ich kei Frag stelle?", "Kann ich keine Frage stellen?"),
    ],
    lesson: "small-word",
    listen: { word: "e", means: "eine" },
  },
];
