import { DISPLAY } from "@/lib/variety/display";
import { project } from "@/lib/geo/region";
import { REGIONS } from "@/lib/geo/regions";

/**
 * The product's subject, drawn: where Heidi speaks, and where it does not yet.
 *
 * This replaced an abstract figure of irregular patches. That figure argued in
 * its own comment that a map of Switzerland would be "a cartographic claim"
 * and therefore dishonest — which had the worry right and the conclusion
 * backwards. The answer to "an inaccurate map would mislead" is an accurate
 * one, and the result of avoiding it was a black blob crossed by a red line
 * that told a reader nothing at all. A picture nobody can read is not the
 * cautious choice.
 *
 * What makes this honest:
 *
 *   - The border is real — Natural Earth, generated by `scripts/build-region.mjs`,
 *     not drawn by hand until it looked Swiss.
 *   - The dialects are POINTS, not territories. Isoglosses do not follow
 *     cantonal borders and we draw no boundary implying they do. "Bernese is
 *     spoken at Bern" is all that is claimed, and that is true.
 *   - Zurich is filled, the rest are open rings. Solid means "Heidi speaks
 *     this today"; an open ring means "named, not yet covered" — the same
 *     distinction the gate enforces, in the same figure.
 *
 * Still generated from the pack, which was the point of the old one. Nobody
 * opens this file to ship a Bern pack, and a Lesya deployment draws Ukraine by
 * adding one region file.
 *
 * WHAT IT DRAWS NOW, AND WHAT IT USED TO. It drew `family.planned` — the
 * ROADMAP, the dialects Heidi intends to add. Six dots on Switzerland, all
 * accurate, and a reader asked the obvious question: where is Graubünden? The
 * figure was answering "where is Swiss German spoken?" with a product
 * decision, which is not an answer about language at all.
 *
 * So it draws `family.areas`: every German-speaking dialect area in the
 * country, Graubünden and Valais included. The roadmap did not disappear, it
 * became a STATE of a dot rather than the reason a dot exists — filled for the
 * variety Heidi teaches, ringed for one that is coming, faint for one that is
 * simply there. All three are true statements, and now they are three
 * different statements instead of one doing the work of all of them.
 */
export function DialectFigure({ plannedLabel, othersLabel }: { plannedLabel: string; othersLabel: string }) {
  const family = DISPLAY.family;
  const atlas = family?.atlas;
  if (!atlas) return null;

  const region = REGIONS[atlas.region];
  const home = project(atlas.home, region);

  // Every area of the family, each carrying its own point — so nothing is
  // looked up in a second list that could drift from the first.
  const soon = new Set(family?.planned ?? []);
  const areas = DISPLAY.areas
    .filter((area) => !area.taught)
    .map((area) => ({
      id: area.id,
      label: area.town,
      // On the roadmap, or simply on the map. The difference is drawn, not
      // hidden: a reader can see which ones Heidi is actually coming for.
      // By id. Matching on the town name is what drew Aarau and Brig as "not
      // on the roadmap" while both sat on it.
      soon: soon.has(area.id),
      ...project(area.place, region),
    }));

  return (
    <figure className="m-0">
      <svg
        viewBox={`0 0 ${region.width} ${region.height}`}
        className="w-full overflow-visible"
        role="img"
        // Three claims, said as three. Calling all ten "planned" was the
        // original conflation surviving into the accessible label, where a
        // sighted reader could not see it was wrong.
        aria-label={[
          `${region.name}: ${DISPLAY.endonym}`,
          `${plannedLabel}: ${areas.filter((a) => a.soon).map((a) => a.label).join(", ")}`,
          `${othersLabel}: ${areas.filter((a) => !a.soon).map((a) => a.label).join(", ")}`,
        ].join(" — ")}
      >
        {/* The country. Filled with the sunk surface so it reads as ground in
            both themes without a second palette. */}
        <path
          d={region.outline}
          className="fill-surface-sunk stroke-border-strong"
          strokeWidth={2}
          strokeLinejoin="round"
        />

        {/* Dialects we do not teach yet: open rings, no fill.
            Their labels sit BELOW the dot while the taught variety's sits
            above — which is what keeps "Züritüütsch" off the Aargau dot 40km
            away, without needing hand-placed offsets in the pack. */}
        {areas.map((d) => (
          <g key={d.id}>
            <circle
              cx={d.x}
              cy={d.y}
              r={11}
              className={
                d.soon
                  ? "fill-surface-page stroke-border-strong"
                  : // Simply there: lighter, because "this exists" and "this is
                    // next" are different claims and should not look alike.
                    "fill-surface-page stroke-border-subtle"
              }
              strokeWidth={2.5}
            />
            <text
              x={d.x}
              y={d.y + 38}
              textAnchor="middle"
              className="fill-fg-muted stroke-surface-sunk font-mono"
              // A halo, so a label crossing the border line stays readable.
              // `paint-order` puts the stroke behind the fill.
              style={{ fontSize: "21px", letterSpacing: "0.08em", strokeWidth: 5, paintOrder: "stroke" }}
            >
              {d.label.toUpperCase()}
            </text>
          </g>
        ))}

        {/* Zurich: filled, larger, and the only label in ink. The one place
            Heidi actually speaks, and it should be obvious at a glance which
            dot that is. */}
        <circle cx={home.x} cy={home.y} r={10} className="fill-accent" />
        <circle cx={home.x} cy={home.y} r={21} className="fill-none stroke-accent" strokeWidth={2.5} />
        <text
          x={home.x}
          y={home.y - 36}
          textAnchor="middle"
          className="fill-fg-primary stroke-surface-sunk font-heading"
          style={{ fontSize: "32px", fontWeight: 700, strokeWidth: 6, paintOrder: "stroke" }}
        >
          {DISPLAY.endonym}
        </text>
      </svg>

      <figcaption className="mt-5 flex flex-col gap-2 sm:flex-row sm:flex-wrap sm:items-center sm:gap-x-5">
        <span className="inline-flex items-center gap-2">
          <span aria-hidden="true" className="inline-block h-3 w-3 rounded-full bg-accent" />
          <span className="font-mono text-caption uppercase tracking-caps text-fg-primary">{DISPLAY.endonym}</span>
        </span>
        <span className="inline-flex items-center gap-2">
          <span
            aria-hidden="true"
            className="inline-block h-3 w-3 rounded-full border-2 border-border-strong bg-surface-page"
          />
          <span className="font-mono text-caption uppercase tracking-caps text-fg-muted">{plannedLabel}</span>
        </span>
        <span className="inline-flex items-center gap-2">
          <span
            aria-hidden="true"
            className="inline-block h-3 w-3 rounded-full border-2 border-border-subtle bg-surface-page"
          />
          <span className="font-mono text-caption uppercase tracking-caps text-fg-muted">{othersLabel}</span>
        </span>
      </figcaption>
    </figure>
  );
}
