import { VARIETY } from "@/lib/variety/active";
import { project } from "@/lib/geo/region";
import { REGIONS } from "@/lib/geo/regions";

/**
 * The product's subject, drawn: where Heidi speaks, and where it does not yet.
 *
 * This replaced an abstract figure of irregular patches. That figure argued in
 * its own comment that a map of Switzerland would be "a cartographic claim"
 * and therefore dishonest — which had the worry right and the conclusion
 * backwards. The answer to "an inaccurate map would mislead" is an accurate
 * one, and the result of avoiding it was a black blob crossed by a red line
 * that told a reader nothing at all. A picture nobody can read is not the
 * cautious choice.
 *
 * What makes this honest:
 *
 *   - The border is real — Natural Earth, generated by `scripts/build-region.mjs`,
 *     not drawn by hand until it looked Swiss.
 *   - The dialects are POINTS, not territories. Isoglosses do not follow
 *     cantonal borders and we draw no boundary implying they do. "Bernese is
 *     spoken at Bern" is all that is claimed, and that is true.
 *   - Zurich is filled, the rest are open rings. Solid means "Heidi speaks
 *     this today"; an open ring means "named, not yet covered" — the same
 *     distinction the gate enforces, in the same figure.
 *
 * Still generated from the pack, which was the point of the old one: the
 * filled dot is `atlas.home`, the rings are `family.planned` looked up in
 * `atlas.places`. Nobody opens this file to ship a Bern pack, and a Lesya
 * deployment draws Ukraine by adding one region file.
 */
export function DialectFigure({ plannedLabel }: { plannedLabel: string }) {
  const family = VARIETY.family;
  const atlas = family?.atlas;
  if (!atlas) return null;

  const region = REGIONS[atlas.region];
  const home = project(atlas.home, region);

  // Only dialects that have a place; the pack test keeps the two lists equal,
  // so this filter is a belt rather than a behaviour.
  const planned = (family?.planned ?? [])
    .map((name) => ({ name, place: atlas.places[name] }))
    .filter((d): d is { name: string; place: NonNullable<typeof d.place> } => Boolean(d.place))
    .map((d) => ({ name: d.name, ...project(d.place, region) }));

  return (
    <figure className="m-0">
      <svg
        viewBox={`0 0 ${region.width} ${region.height}`}
        className="w-full overflow-visible"
        role="img"
        aria-label={`${region.name}: ${VARIETY.endonym} — ${plannedLabel}: ${(family?.planned ?? []).join(", ")}`}
      >
        {/* The country. Filled with the sunk surface so it reads as ground in
            both themes without a second palette. */}
        <path
          d={region.outline}
          className="fill-surface-sunk stroke-border-strong"
          strokeWidth={2}
          strokeLinejoin="round"
        />

        {/* Dialects we do not teach yet: open rings, no fill.
            Their labels sit BELOW the dot while the taught variety's sits
            above — which is what keeps "Züritüütsch" off the Aargau dot 40km
            away, without needing hand-placed offsets in the pack. */}
        {planned.map((d) => (
          <g key={d.name}>
            <circle cx={d.x} cy={d.y} r={11} className="fill-surface-page stroke-border-strong" strokeWidth={2.5} />
            <text
              x={d.x}
              y={d.y + 38}
              textAnchor="middle"
              className="fill-fg-muted stroke-surface-sunk font-mono"
              // A halo, so a label crossing the border line stays readable.
              // `paint-order` puts the stroke behind the fill.
              style={{ fontSize: "21px", letterSpacing: "0.08em", strokeWidth: 5, paintOrder: "stroke" }}
            >
              {d.name.toUpperCase()}
            </text>
          </g>
        ))}

        {/* Zurich: filled, larger, and the only label in ink. The one place
            Heidi actually speaks, and it should be obvious at a glance which
            dot that is. */}
        <circle cx={home.x} cy={home.y} r={10} className="fill-accent" />
        <circle cx={home.x} cy={home.y} r={21} className="fill-none stroke-accent" strokeWidth={2.5} />
        <text
          x={home.x}
          y={home.y - 36}
          textAnchor="middle"
          className="fill-fg-primary stroke-surface-sunk font-heading"
          style={{ fontSize: "32px", fontWeight: 700, strokeWidth: 6, paintOrder: "stroke" }}
        >
          {VARIETY.endonym}
        </text>
      </svg>

      <figcaption className="mt-5 flex flex-col gap-2 sm:flex-row sm:flex-wrap sm:items-center sm:gap-x-5">
        <span className="inline-flex items-center gap-2">
          <span aria-hidden="true" className="inline-block h-3 w-3 rounded-full bg-accent" />
          <span className="font-mono text-[11px] uppercase tracking-caps text-fg-primary">{VARIETY.endonym}</span>
        </span>
        <span className="inline-flex items-center gap-2">
          <span
            aria-hidden="true"
            className="inline-block h-3 w-3 rounded-full border-2 border-border-strong bg-surface-page"
          />
          <span className="font-mono text-[11px] uppercase tracking-caps text-fg-muted">{plannedLabel}</span>
        </span>
      </figcaption>
    </figure>
  );
}
